package com.tracker.spring.rest.entity;



import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;


@Entity
@Table(name = "students")
@ApiModel(description = "data model of student entity")
public class Student {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "student id generated by db", position = 1)
    @Column(name = "id")
    private int id;
    @ApiModelProperty(value = "first name of student", example = "Ivan",position = 2)
    @Column(name = "name")
    private String name;
    @ApiModelProperty(value = "lastname name of student", example = "Taburetkin",position = 3)
    @Column(name = "surname")
    private String surname;

    public Student() {

    }

    public Student(String name, String surname) {
        this.name = name;
        this.surname = surname;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                '}';
    }
}
