package com.tracker.spring.rest.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "tasks")
@ApiModel(description = "data model of task entity")
public class Task {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "task id generated by db", position = 1)
    @Column(name = "id")
    private long id;

    @ApiModelProperty(value = "description of task", example = "some description", position = 2)
    @Column(name = "description")
    private String description;

    @ApiModelProperty(value = "time of task", example = "10:30", position = 3)
    @Column(name = "time")
    private String time;


    public Task() {
    }

    public Task(String description, String time) {
        this.description = description;
        this.time = time;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @Override
    public String toString() {
        return "Task{" +
                "id=" + id +
                ", description='" + description + '\'' +
                ", time='" + time + '\'' +
                '}';
    }
}
